//
//  RescueChatMessage.h
//  RescueSDK
//
//  Copyright (c) 2003-2015 LogMeIn Inc. All rights reserved.
//

/**
 @brief  Types of chat messages
 */
typedef NS_ENUM(NSInteger, RescueChatMessageType){
    /// status messsage generated by the SDK
    RescueChatMessageTypeSystem,
    /// chat message from the user
    RescueChatMessageTypeUser,
    /// chat message from the technician
    RescueChatMessageTypeTechnician,
};

/**
 @brief  Chat message
 */
@interface RescueChatMessage : NSObject

/**
 @brief  The chat message string.
 */
@property (nonatomic, strong, readonly) NSString *message;

/**
 @brief  Type of the chat message.
 */
@property (nonatomic, readonly) RescueChatMessageType type;

/**
 @brief  Date-time of the creation of the chat message
 */
@property (nonatomic, strong, readonly) NSDate *date;

@end
