//
//  RescueChatMessage.h
//  RescueSDK
//
//  Copyright (c) 2003-2016 LogMeIn Inc. All rights reserved.
//

#import <Foundation/Foundation.h>


/**
 @brief  Types of chat messages
 */
typedef NS_ENUM(NSUInteger, RescueChatMessageType){
    /// status messsage generated by the SDK
    RescueChatMessageTypeSystem,
    /// chat message from the user
    RescueChatMessageTypeUser,
    /// chat message from the technician
    RescueChatMessageTypeTechnician,
};

/**
 @brief  Chat message
 */
@interface RescueChatMessage : NSObject <NSCoding>

/**
 @brief  The chat message string.
 */
@property (nonatomic, strong) NSString *message;

/**
 @brief  Type of the chat message.
 */
@property (nonatomic) RescueChatMessageType type;

/**
 @brief  Date-time of the creation of the chat message
 */
@property (nonatomic, strong) NSDate *date;

@end
